name: tests_normalized_sequential
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      run: |
        pip3 install -r requirements.txt
    - name: docker
      run: |
        git submodule init
        git submodule update
        docker compose up -d --build
        docker ps -a
        sleep 20

        # CREATE DATABASES
        docker exec -i twitter_postgres_parallel-pg_normalized psql -U postgres -c "CREATE DATABASE pg_normalized;"
        docker exec -i twitter_postgres_parallel-pg_normalized psql -U postgres -c "CREATE DATABASE pg_denormalized;"

        # LOAD SCHEMAS
        docker exec -i twitter_postgres_parallel-pg_normalized psql -U postgres -d pg_normalized -f services/pg_normalized/schema.sql
        docker exec -i twitter_postgres_parallel-pg_normalized psql -U postgres -d pg_denormalized -f services/pg_normalized/schema.sql

        # RUN YOUR SCRIPT
        ./load_tweets_sequential.sh

        # RUN TESTS
        docker compose exec -T pg_normalized ./run_tests.sh
        ./load_tweets_sequential.sh
        docker compose exec -T pg_normalized ./run_tests.sh
